version: "3.8"

services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: bookstore
    volumes:
      - ./backend/uploads:/app/uploads
      - /app/node_modules
    command: npm run start:dev
  
  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app       
      - /app/node_modules
    command: npm run dev
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
